# Generated by Django 5.0.4 on 2024-11-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
